[package]
name = "transacty"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
derive_more = "0.99.17"
once_cell = "1.10.0"
regex = "1.5.4"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"

[dev-dependencies]
proptest = "1.0.0"
